-- Aufgabenplaner: persönliche Bezeichnungen für die 6 Aufgaben-Farben
-- Ein Datensatz pro user_id mit Spalten col1_txt … col6_txt
--
-- Farbnummern pro Aufgabe: tasks.color_key / week_plan.color_key → siehe tasks_week_plan_color_key.sql
--
-- In Supabase SQL Editor ausführen, falls noch nicht vorhanden.

CREATE TABLE IF NOT EXISTS public.task_colors_indiv (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL UNIQUE,
  col1_txt text,
  col2_txt text,
  col3_txt text,
  col4_txt text,
  col5_txt text,
  col6_txt text
);

ALTER TABLE public.task_colors_indiv ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "task_colors_indiv_select_public" ON public.task_colors_indiv;
DROP POLICY IF EXISTS "task_colors_indiv_insert_public" ON public.task_colors_indiv;
DROP POLICY IF EXISTS "task_colors_indiv_update_public" ON public.task_colors_indiv;
DROP POLICY IF EXISTS "task_colors_indiv_delete_public" ON public.task_colors_indiv;

CREATE POLICY "task_colors_indiv_select_public"
  ON public.task_colors_indiv
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "task_colors_indiv_insert_public"
  ON public.task_colors_indiv
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "task_colors_indiv_update_public"
  ON public.task_colors_indiv
  FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "task_colors_indiv_delete_public"
  ON public.task_colors_indiv
  FOR DELETE
  TO anon, authenticated
  USING (true);
