-- week_plan: Wochenplan-Aufgaben (user_id = profiles.username).
-- Erwartete Spalten: id, user_id, task, plan_day (date), start_time, end_time, done, color_key (1–6, Default 1)
--
-- Beispiel (falls noch nicht angelegt):
-- CREATE TABLE public.week_plan (
--   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   user_id text NOT NULL,
--   task text NOT NULL,
--   plan_day date NOT NULL,
--   start_time time NOT NULL,
--   end_time time NOT NULL,
--   done boolean NOT NULL DEFAULT false
-- );

ALTER TABLE public.week_plan ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "week_plan_select_public" ON public.week_plan;
DROP POLICY IF EXISTS "week_plan_insert_public" ON public.week_plan;
DROP POLICY IF EXISTS "week_plan_update_public" ON public.week_plan;
DROP POLICY IF EXISTS "week_plan_delete_public" ON public.week_plan;

CREATE POLICY "week_plan_select_public"
  ON public.week_plan
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "week_plan_insert_public"
  ON public.week_plan
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "week_plan_update_public"
  ON public.week_plan
  FOR UPDATE
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "week_plan_delete_public"
  ON public.week_plan
  FOR DELETE
  TO anon, authenticated
  USING (true);
